src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TicketRepository::class)
 */
class Ticket
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")

     *  @Assert\NotNull
     */
    private $numero;

    /**
     * @ORM\Column(type="integer")

     *  @Assert\NotNull
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=255)

     *  @Assert\NotNull
     * @Assert\Length(min=3)
     */
    private $destination;

     /**
     * @ORM\Column(type="date")
     */
    private $Date;

   /**
     * @ORM\Column(type="date")
     */
    private $Heure;
        /**
     * @ORM\Column(type="integer")
   
  
     */
    private $id_evenement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function setNumero(int $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getNombre(): ?int
    {
        return $this->nombre;
    }

    public function setNombre(int $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(string $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getHeure(): ?\DateTimeInterface
    {
        return $this->Heure;
    }

    public function setHeure(\DateTimeInterface $Heure): self
    {
        $this->Heure = $Heure;

        return $this;
    }
    public function getIdEvenement(): ?int
    {
        return $this->id_evenement;
    }

    public function setIdEvenement(int $id_evenement): self
    {
        $this->id_evenement = $id_evenement;

        return $this;
    }
}

src/Form/TicketType.php
<?php

namespace App\Form;

use App\Entity\Ticket;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TicketType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('numero')
            ->add('nombre')
            ->add('destination')
            ->add('Date')
            ->add('Heure')
            ->add('id_evenement')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ticket::class,
        ]);
    }
}

src/Controller/TicketController.php
<?php

namespace App\Controller;

use App\Entity\Ticket;
use App\Form\TicketType;
use App\Repository\TicketRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ticket")
 */
class TicketController extends AbstractController
{
    /**
     * @Route("/", name="ticket_index", methods={"GET"})
     */
    public function index(TicketRepository $ticketRepository): Response
    {
        return $this->render('ticket/index.html.twig', [
            'tickets' => $ticketRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id_evenement}/new", name="ticket_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $ticket = new Ticket();
        $form = $this->createForm(TicketType::class, $ticket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($ticket);
            $entityManager->flush();

            return $this->redirectToRoute('ticket_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('ticket/new.html.twig', [
            'ticket' => $ticket,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ticket_show", methods={"GET"})
     */
    public function show(Ticket $ticket): Response
    {
        return $this->render('ticket/show.html.twig', [
            'ticket' => $ticket,
        ]);
    }
/**
     * @Route("/searchTicket", name="Ticket_search")
     */
    public function searchTicket(Request $request)
    {
        $ticket=   $request->get('ticket');
        $em=$this->getDoctrine()->getManager();
        if($ticket == ""){
            $tickets=$em->getRepository(ticket::class)->findAll();
        }else{
            $tickets=$em->getRepository(ticket::class)->findBy(
                ['numero'=> $ticket]
            );
        }

        return $this->render('ticket/index.html.twig', array(
            'tickets' => $tickets
        ));

    }
    /**
     * @Route("/{id}/edit", name="ticket_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Ticket $ticket, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TicketType::class, $ticket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('ticket_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('ticket/edit.html.twig', [
            'ticket' => $ticket,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ticket_delete", methods={"POST"})
     */
    public function delete(Request $request, Ticket $ticket, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ticket->getId(), $request->request->get('_token'))) {
            $entityManager->remove($ticket);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ticket_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/ticket/_delete_form.html.twig
<form method="post" action="{{ path('ticket_delete', {'id': ticket.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ticket.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ticket/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/ticket/edit.html.twig
{% extends 'layoutBackOffice.html.twig' %}
{% block title %} Show des tickets{% endblock %}

{% block body %}
<body class="bg-gradient-primary">

<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">New Formation</h1>
                        </div>


    <h1>Edit Ticket</h1>

    {{ include('ticket/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('ticket_index') }}">back to list</a>

    {{ include('ticket/_delete_form.html.twig') }}

                        </div>
                </div>

            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

templates/ticket/index.html.twig
{% extends 'layoutBackOffice.html.twig' %}

{% block title %} Liste des tickets{% endblock %}


{% block body %}

  <!-- Begin Page Content -->
                <div class="container-fluid">

            

                
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                             <form method="post" action="{{ path('Ticket_search') }}">
                    <input type="text" name="ticket" placeholder="ticket " />
                    <input type="submit" value="chercher">
                </form>
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                               <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Numero</th>
                                        <th>Nombre</th>
                                        <th>Destination</th>
                                        <th>Date</th>
                                        <th>Heure</th>
                                        <th>Id_evenement</th>
                                        <th>actions</th>
                                    </tr>
                                </thead>
                                     <tbody>
                                    {% for ticket in tickets %}
                                        <tr>
                                            <td>{{ ticket.id }}</td>
                                            <td>{{ ticket.numero }}</td>
                                            <td>{{ ticket.nombre }}</td>
                                            <td>{{ ticket.destination }}</td>
                                            <td>{{ ticket.Date ? ticket.Date|date('Y-m-d') : '' }}</td>
                                            <td>{{ ticket.Heure ? ticket.Heure|date('Y-m-d') : '' }}</td>
                                            <td>{{ ticket.idEvenement }}</td>
                                            <td>
                                                         <a  href="{{ path('ticket_show', {'id': ticket.id}) }}"class="btn btn-success btn-circle ">
                                        <i class="fas fa-check"></i>
                                    </a>
                 <a  href="{{ path('ticket_edit', {'id': ticket.id}) }}" class="btn btn-warning btn-circle ">
                                        <i class="fas fa-exclamation-triangle"></i>
                                    </a>
                                    <a href="{{ path('ticket_delete', {'id': ticket.id}) }}" class="btn btn-danger btn-circle">
                                        <i class="fas fa-trash"></i>
                                    </a>
                
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="7">no records found</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->




    
{% endblock %}

templates/ticket/new.html.twig
{% extends 'layoutFrontOffice.html.twig' %}

{% block title %} Ticket{% endblock %}


{% block body %}
   <body class="bg-gradient-primary">

<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">New Ticket</h1>
                        </div>


    {{ include('ticket/_form.html.twig') }}
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
</body>
  
{% endblock %}

templates/ticket/show.html.twig
{% extends 'layoutBackOffice.html.twig' %}
{% block title %} Show des tickets{% endblock %}

{% block body %}
    <h1>Ticket</h1>
    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                        </div>
                        <div class="card-body">
                          <div class="imprimer">
      	<input id="impression"class="btn btn-success waves-effect" name="impression" type="submit" onclick="imprimer_page()" value="Exporter en pdf " />
      </div>
 
       <script type="text/javascript">
            function imprimer_page(){
            window.print();
             }
        </script>
        </div>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ticket.id }}</td>
            </tr>
            <tr>
                <th>Numero</th>
                <td>{{ ticket.numero }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ ticket.nombre }}</td>
            </tr>
            <tr>
                <th>Destination</th>
                <td>{{ ticket.destination }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ ticket.Date ? ticket.Date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Heure</th>
                <td>{{ ticket.Heure ? ticket.Heure|date('Y-m-d') : '' }}</td>
            </tr>
             <tr>
                <th>Id_ticket</th>
                <td>{{ ticket.idEvenement }}</td>
            </tr>
        </tbody>
    </table>
      <a href="{{ path('ticket_index') }}" class="btn btn-secondary btn-icon-split">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-arrow-right"></i>
                                        </span>
                                        <span class="text">Back To list</span>
                                    </a>
  &nbsp; 
<a href="{{ path('ticket_edit', {'id': ticket.id}) }}" class="btn btn-warning btn-icon-split">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-exclamation-triangle"></i>
                                        </span>
                                        <span class="text">Modifier</span>
                                    </a>
                           
 </div>
                    </div>

                </div>
  
{% endblock %}